[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "livekit-agents[openai]>=1.0.23",
    "python-dotenv>=1.1.0",
]
